export const SET_NAV_ENVIRONMENT = "SET_NAV_ENVIRONMENT"
export const GET_LIST_TECHNO = "GET_LIST_TECHNO"
export const GET_LIST_CREATION = "GET_LIST_CREATION"
export const GET_LIST_CREA_TO_TECH = "GET_LIST_CREA_TO_TECH"
